-
  name: Eval
  match: '^/eval(?:/(?<expr>.+))?$'
  body: |
    #{eval(context['expr'])}

-
  name: Forbidden
  match: '(?:\.md|\.yml)$'
  status: 403
  body: forbidden

-
  name: Assets
  description: /tmp/cmsに書き出されたリソースを表示するため
  match: '(?:\.jpg|\.png|\.svg)$'
  status: 399

-
  name: Css
  match: '\.css$'
  handler: sass.sh
  content_type: text/css; charset=utf-8
  condition: |
    !`find html#{context['uri'].sub(/\.css$/, '.s[ac]ss')}`.empty?

-
  name: Xml
  match: '^(?<uri>/(?<view>.*\.xml))$'
  handler: page.php
  content_type: application/xml; charset=utf-8
  condition: |
    File.exists?("html#{context['uri']}.php")

-
  name: Html
  match: '^(?<uri>/(?<view>.*\.html))$'
  handler: page.php
  condition: |
    File.exists?("html#{context['uri']}.php")
